/**
 * In-bot strategy engine.
 *
 * Polls the sai-keeper oracle for live prices on a configurable interval,
 * maintains a rolling close-price buffer per running strategy, runs one of
 * a handful of indicator strategies on each tick, and fires openTrade /
 * closeTrade when the indicator signals a state change.
 *
 * Each strategy is identified by a stable id (autogenerated as <type>-<n>)
 * and is independent — separate timer, separate price buffer, separate
 * inflight mutex. A strategy "owns" its (marketId, long?) slot: its reversal
 * logic uses closeTrade({marketId, long}) which closes whichever trade the
 * user has open in that slot. Operators running multiple strategies on the
 * same market need to coordinate manually.
 *
 * Strategy specs (NOT in-memory state) persist to strategies.json so they
 * survive restarts. Price history and signal state do NOT persist — they
 * re-warm from oracle on resume.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { z } from "zod"
import { fetchBorrowing } from "./sai-keeper"
import { openTrade, closeTrade } from "./trade"
import type { SignerCtx } from "./wallet"
import type { AppConfig } from "./config"
import { recordEvent, isKilled, isDryRun } from "./events"

// ---------- spec ----------

export const StrategyType = z.enum([
  "ema_cross",
  "rsi_reversion",
  "bb_breakout",
  "macd_cross",
  "donchian_breakout",
])
export type StrategyType = z.infer<typeof StrategyType>

const NumericParams = z.record(z.string(), z.number().finite())

export const StrategySpecSchema = z.object({
  id: z.string().min(1).optional(),
  type: StrategyType,
  marketId: z.number().int().nonnegative(),
  intervalSec: z.number().int().min(5).max(86400),
  leverage: z.union([z.number().min(1), z.string()]),
  amountUsdc: z.union([z.number(), z.string()]).transform((v) => String(v)),
  slippagePct: z
    .union([z.number(), z.string()])
    .optional()
    .transform((v) => (v === undefined ? "1" : String(v))),
  params: NumericParams.default({}),
})
export type StrategySpec = z.infer<typeof StrategySpecSchema>

// ---------- view (serializable snapshot of a running strategy) ----------

export type StrategyView = {
  id: string
  type: StrategyType
  marketId: number
  intervalSec: number
  leverage: number | string
  amountUsdc: string
  slippagePct: string
  params: Record<string, number>
  startedAt: number
  lastTickAt: number | null
  tickCount: number
  bufferLen: number
  warmupNeeded: number
  warmedUp: boolean
  lastPrice: number | null
  lastSignal: SignalState | null
  inflight: boolean
  lastError: string | null
}

type SignalState = "long" | "short" | "flat"

type Running = {
  spec: StrategySpec
  id: string
  prices: number[]
  startedAt: number
  lastTickAt: number | null
  tickCount: number
  lastSignal: SignalState | null
  inflight: boolean
  lastError: string | null
  lastPrice: number | null
  timer: NodeJS.Timeout | null
}

// ---------- indicator strategies ----------

type IndicatorResult = {
  target: SignalState | null // null = not enough data
  meta?: Record<string, number>
}

type Indicator = {
  warmup: (params: Record<string, number>) => number
  evaluate: (prices: number[], params: Record<string, number>) => IndicatorResult
}

function sma(arr: number[], len: number): number {
  let s = 0
  for (let i = arr.length - len; i < arr.length; i++) s += arr[i]!
  return s / len
}

function emaSeries(arr: number[], len: number): number[] {
  if (arr.length < len) return []
  const k = 2 / (len + 1)
  const out: number[] = []
  // Seed with SMA of the first `len` samples (standard EMA seeding).
  let prev = sma(arr.slice(0, len), len)
  out.push(prev)
  for (let i = len; i < arr.length; i++) {
    prev = arr[i]! * k + prev * (1 - k)
    out.push(prev)
  }
  return out
}

function rsiSeries(arr: number[], len: number): number[] {
  if (arr.length < len + 1) return []
  const gains: number[] = []
  const losses: number[] = []
  for (let i = 1; i < arr.length; i++) {
    const d = arr[i]! - arr[i - 1]!
    gains.push(d > 0 ? d : 0)
    losses.push(d < 0 ? -d : 0)
  }
  // Wilder's smoothing: first avg = mean of first `len` deltas, then EMA-like
  let avgG = gains.slice(0, len).reduce((a, b) => a + b, 0) / len
  let avgL = losses.slice(0, len).reduce((a, b) => a + b, 0) / len
  const out: number[] = []
  const compute = () => {
    if (avgL === 0) return 100
    const rs = avgG / avgL
    return 100 - 100 / (1 + rs)
  }
  out.push(compute())
  for (let i = len; i < gains.length; i++) {
    avgG = (avgG * (len - 1) + gains[i]!) / len
    avgL = (avgL * (len - 1) + losses[i]!) / len
    out.push(compute())
  }
  return out
}

const INDICATORS: Record<StrategyType, Indicator> = {
  ema_cross: {
    warmup: (p) => Math.max(p.slowLen ?? 21, p.fastLen ?? 9) + 1,
    evaluate: (prices, p) => {
      const fastLen = p.fastLen ?? 9
      const slowLen = p.slowLen ?? 21
      const fast = emaSeries(prices, fastLen)
      const slow = emaSeries(prices, slowLen)
      if (fast.length === 0 || slow.length === 0) return { target: null }
      const f = fast[fast.length - 1]!
      const s = slow[slow.length - 1]!
      return {
        target: f > s ? "long" : f < s ? "short" : "flat",
        meta: { fast: f, slow: s },
      }
    },
  },

  rsi_reversion: {
    warmup: (p) => (p.len ?? 14) + 2,
    evaluate: (prices, p) => {
      const len = p.len ?? 14
      const os = p.oversold ?? 30
      const ob = p.overbought ?? 70
      const series = rsiSeries(prices, len)
      if (series.length === 0) return { target: null }
      const r = series[series.length - 1]!
      const target: SignalState = r <= os ? "long" : r >= ob ? "short" : "flat"
      return { target, meta: { rsi: r } }
    },
  },

  bb_breakout: {
    warmup: (p) => p.len ?? 20,
    evaluate: (prices, p) => {
      const len = p.len ?? 20
      const mult = p.mult ?? 2
      if (prices.length < len) return { target: null }
      const window = prices.slice(-len)
      const basis = window.reduce((a, b) => a + b, 0) / len
      let varSum = 0
      for (const x of window) varSum += (x - basis) ** 2
      const stdev = Math.sqrt(varSum / len)
      const upper = basis + mult * stdev
      const lower = basis - mult * stdev
      const close = prices[prices.length - 1]!
      const target: SignalState =
        close > upper ? "long" : close < lower ? "short" : "flat"
      return { target, meta: { basis, upper, lower, close } }
    },
  },

  macd_cross: {
    warmup: (p) =>
      Math.max(p.fastLen ?? 12, p.slowLen ?? 26) + (p.signalLen ?? 9) + 1,
    evaluate: (prices, p) => {
      const fastLen = p.fastLen ?? 12
      const slowLen = p.slowLen ?? 26
      const signalLen = p.signalLen ?? 9
      const fast = emaSeries(prices, fastLen)
      const slow = emaSeries(prices, slowLen)
      // Align EMA series at the right edge (same last index = same time).
      const n = Math.min(fast.length, slow.length)
      if (n < signalLen) return { target: null }
      const macd: number[] = []
      for (let i = 0; i < n; i++) {
        macd.push(fast[fast.length - n + i]! - slow[slow.length - n + i]!)
      }
      const signal = emaSeries(macd, signalLen)
      if (signal.length === 0) return { target: null }
      const m = macd[macd.length - 1]!
      const s = signal[signal.length - 1]!
      const target: SignalState = m > s ? "long" : m < s ? "short" : "flat"
      return { target, meta: { macd: m, signal: s } }
    },
  },

  donchian_breakout: {
    warmup: (p) => (p.len ?? 20) + 1,
    evaluate: (prices, p) => {
      const len = p.len ?? 20
      if (prices.length < len + 1) return { target: null }
      // Exclude the current price from the channel window so a new high/low
      // genuinely breaks the previous N-bar range.
      const ref = prices.slice(-len - 1, -1)
      const high = Math.max(...ref)
      const low = Math.min(...ref)
      const close = prices[prices.length - 1]!
      const target: SignalState =
        close > high ? "long" : close < low ? "short" : "flat"
      return { target, meta: { high, low, close } }
    },
  },
}

// ---------- engine state ----------

type Deps = {
  signer: SignerCtx
  app: AppConfig
}

let deps: Deps | null = null
let storePath: string | null = null
const running = new Map<string, Running>()
let idCounter = 1

function nextId(type: StrategyType): string {
  while (running.has(`${type}-${idCounter}`)) idCounter++
  return `${type}-${idCounter++}`
}

function snapshotView(r: Running): StrategyView {
  const ind = INDICATORS[r.spec.type]
  const warmup = ind.warmup(r.spec.params)
  return {
    id: r.id,
    type: r.spec.type,
    marketId: r.spec.marketId,
    intervalSec: r.spec.intervalSec,
    leverage: r.spec.leverage,
    amountUsdc: r.spec.amountUsdc,
    slippagePct: r.spec.slippagePct as string,
    params: r.spec.params,
    startedAt: r.startedAt,
    lastTickAt: r.lastTickAt,
    tickCount: r.tickCount,
    bufferLen: r.prices.length,
    warmupNeeded: warmup,
    warmedUp: r.prices.length >= warmup,
    lastPrice: r.lastPrice,
    lastSignal: r.lastSignal,
    inflight: r.inflight,
    lastError: r.lastError,
  }
}

function persist(): void {
  if (!storePath) return
  const out = [...running.values()].map((r) => ({ ...r.spec, id: r.id }))
  try {
    writeFileSync(storePath, JSON.stringify(out, null, 2))
  } catch {
    // Best-effort; not fatal.
  }
}

// ---------- tick ----------

const MAX_BUFFER = 500 // hard cap — every indicator we ship needs ≪ 100

async function tick(r: Running): Promise<void> {
  if (!deps) return
  if (r.inflight) return
  r.inflight = true
  try {
    const borrowing = await fetchBorrowing(
      deps.app.cfg.saiKeeperEndpoint,
      r.spec.marketId,
      deps.app.cfg.usdcTokenIndex,
    )
    if (!borrowing.isOpen) {
      r.lastError = `market ${r.spec.marketId} closed`
      return
    }
    r.lastError = null
    r.lastPrice = borrowing.price
    r.prices.push(borrowing.price)
    if (r.prices.length > MAX_BUFFER) r.prices.splice(0, r.prices.length - MAX_BUFFER)
    r.lastTickAt = Date.now()
    r.tickCount += 1

    const ind = INDICATORS[r.spec.type]
    const result = ind.evaluate(r.prices, r.spec.params)
    if (result.target === null) return // still warming up

    if (result.target === r.lastSignal) return // no change

    if (isKilled()) {
      recordEvent({
        source: "strategy",
        action: "rejected",
        marketId: r.spec.marketId,
        status: "blocked",
        message: `[${r.id}] kill switch engaged — skipping ${r.lastSignal ?? "flat"} → ${result.target}`,
      })
      return
    }

    // Step 1: close opposite if needed.
    if (
      (result.target === "long" && r.lastSignal === "short") ||
      (result.target === "short" && r.lastSignal === "long") ||
      (result.target === "flat" && (r.lastSignal === "long" || r.lastSignal === "short"))
    ) {
      const longBeingClosed = r.lastSignal === "long"
      const closeRes = await closeTrade(
        deps.signer,
        { marketId: r.spec.marketId, long: longBeingClosed },
        { dryRun: isDryRun(), explorer: deps.app.cfg.explorerTx },
      )
      recordEvent({
        source: "strategy",
        action: "close",
        marketId: r.spec.marketId,
        status: closeRes.status,
        txHash: closeRes.txHash,
        explorer: closeRes.explorer,
        message: `[${r.id}] ${r.lastSignal} → ${result.target}: ${closeRes.message}`,
      })
    }

    // Step 2: open new direction if not going flat.
    if (result.target === "long" || result.target === "short") {
      const openRes = await openTrade(
        deps.signer,
        {
          marketId: r.spec.marketId,
          long: result.target === "long",
          leverage: r.spec.leverage,
          amountUsdc: r.spec.amountUsdc,
          slippagePct: r.spec.slippagePct,
        },
        { dryRun: isDryRun(), explorer: deps.app.cfg.explorerTx },
      )
      recordEvent({
        source: "strategy",
        action: result.target === "long" ? "open_long" : "open_short",
        marketId: openRes.marketId,
        base: openRes.base,
        quote: openRes.quote,
        leverage: r.spec.leverage,
        amountUsdc: r.spec.amountUsdc,
        status: openRes.status,
        txHash: openRes.txHash,
        explorer: openRes.explorer,
        message: `[${r.id}] entered ${result.target.toUpperCase()}: ${openRes.message}`,
      })
    } else {
      recordEvent({
        source: "strategy",
        action: "signal",
        marketId: r.spec.marketId,
        status: isDryRun() ? "dry-run" : "broadcast",
        message: `[${r.id}] ${r.lastSignal ?? "—"} → flat`,
      })
    }

    r.lastSignal = result.target
  } catch (err) {
    const msg = (err as Error).message
    r.lastError = msg
    recordEvent({
      source: "strategy",
      action: "rejected",
      marketId: r.spec.marketId,
      status: "error",
      message: `[${r.id}] tick error: ${msg}`,
    })
  } finally {
    r.inflight = false
  }
}

// ---------- public api ----------

export function initStrategies(d: Deps, opts?: { storeFile?: string }): void {
  deps = d
  storePath = opts?.storeFile ?? resolve(process.cwd(), "strategies.json")
  if (existsSync(storePath)) {
    try {
      const raw = readFileSync(storePath, "utf8")
      const arr = JSON.parse(raw) as unknown[]
      for (const item of arr) {
        const parsed = StrategySpecSchema.safeParse(item)
        if (!parsed.success) continue
        startStrategyInternal(parsed.data, { persistAfter: false })
      }
    } catch {
      // Corrupt file — start fresh; don't overwrite until next save.
    }
  }
}

export function listStrategies(): StrategyView[] {
  return [...running.values()].map(snapshotView)
}

function startStrategyInternal(
  spec: StrategySpec,
  opts: { persistAfter: boolean },
): StrategyView {
  if (!deps) throw new Error("strategies not initialized")
  const id = spec.id && !running.has(spec.id) ? spec.id : nextId(spec.type)
  const r: Running = {
    spec: { ...spec, id },
    id,
    prices: [],
    startedAt: Date.now(),
    lastTickAt: null,
    tickCount: 0,
    lastSignal: null,
    inflight: false,
    lastError: null,
    lastPrice: null,
    timer: null,
  }
  running.set(id, r)
  // First tick fires immediately so warmup begins, then on the interval.
  tick(r).catch(() => {})
  r.timer = setInterval(() => { tick(r).catch(() => {}) }, spec.intervalSec * 1000)
  if (opts.persistAfter) persist()
  return snapshotView(r)
}

export function startStrategy(input: unknown): StrategyView {
  const spec = StrategySpecSchema.parse(input)
  return startStrategyInternal(spec, { persistAfter: true })
}

export function stopStrategy(id: string): boolean {
  const r = running.get(id)
  if (!r) return false
  if (r.timer) clearInterval(r.timer)
  running.delete(id)
  persist()
  return true
}

export function stopAllStrategies(): void {
  for (const r of running.values()) {
    if (r.timer) clearInterval(r.timer)
  }
  running.clear()
  persist()
}

/**
 * Inputs metadata for the dashboard — strategy types and the param fields
 * each one accepts. Single source of truth so the UI doesn't reinvent.
 */
export const STRATEGY_CATALOG: Array<{
  type: StrategyType
  label: string
  description: string
  params: Array<{ key: string; label: string; default: number; step?: number; min?: number }>
}> = [
  {
    type: "ema_cross",
    label: "EMA crossover",
    description:
      "Long when fast EMA > slow EMA, short when below. Trend-following on the oracle's spot price.",
    params: [
      { key: "fastLen", label: "fast EMA length", default: 9, min: 2 },
      { key: "slowLen", label: "slow EMA length", default: 21, min: 3 },
    ],
  },
  {
    type: "rsi_reversion",
    label: "RSI mean reversion",
    description:
      "Long when RSI ≤ oversold, short when ≥ overbought, flat in between. Counter-trend.",
    params: [
      { key: "len", label: "RSI length", default: 14, min: 2 },
      { key: "oversold", label: "oversold", default: 30, min: 1 },
      { key: "overbought", label: "overbought", default: 70, min: 1 },
    ],
  },
  {
    type: "bb_breakout",
    label: "Bollinger breakout",
    description:
      "Long above upper band, short below lower, flat between. Breakout / volatility expansion.",
    params: [
      { key: "len", label: "length", default: 20, min: 5 },
      { key: "mult", label: "stdev mult", default: 2, step: 0.1, min: 0.5 },
    ],
  },
  {
    type: "macd_cross",
    label: "MACD signal cross",
    description: "Long when MACD line > signal line, short otherwise. Momentum follow.",
    params: [
      { key: "fastLen", label: "fast", default: 12, min: 2 },
      { key: "slowLen", label: "slow", default: 26, min: 3 },
      { key: "signalLen", label: "signal", default: 9, min: 2 },
    ],
  },
  {
    type: "donchian_breakout",
    label: "Donchian breakout",
    description:
      "Long on new N-bar high (excludes current), short on new N-bar low. Classic turtle-style.",
    params: [
      { key: "len", label: "channel length", default: 20, min: 3 },
    ],
  },
]
